# This toml file defines the default values of the options.

precision = ['high', 'medium']
pair_style = [
    'eam/alloy', 'eam/fs', 'eam/adp', 'tersoff',
    'atomic/deepmd', 'atomic/sf', 'atomic/grap'
]

[nn.atomic]
activation = ["leaky_relu", 'relu', 'tanh', 'softsign', 'softplus', 'sigmoid', 'linear', 'elu']
kernel_initializer = [
    'he_normal', 'he_uniform',
    'random_normal', 'random_uniform',
    'lecun_normal', 'lecun_uniform',
    'glorot_normal', 'glorot_uniform',
    'xavier_normal', 'xavier_uniform',
    'truncated_normal']

[nn.atomic.finite_temperature]
algorithm = ["off", "zero", "semi", "full"]
activation = ["leaky_relu", 'relu', 'tanh', 'softsign', 'softplus', 'sigmoid', 'linear', 'elu']

[nn.atomic.sf]
cutoff_function = ["cosine", "polynomial"]

[nn.atomic.grap]
algorithm = ['sf', 'density', 'morse', 'pexp']
cutoff_function = ['cosine', 'polynomial']
param_space_method = ["pair", "cross"]

[nn.loss.energy]
method = ["rmse", "logcosh"]

[nn.loss.eentropy]
method = ["rmse", "logcosh"]

[nn.loss.free_energy]
method = ["rmse", "logcosh"]

[nn.loss.forces]
method = ["rmse", "logcosh"]

[nn.loss.stress]
method = ["rmse", "logcosh", "rrmse"]

[nn.loss.total_pressure]
method = ["rmse", "logcosh"]

[nn.loss.ediff]
method = ["mae", "logcosh"]

[opt]
method = ["adam", 'rmsprop', 'adadelta', 'nadam', 'sgd', 'adamw']
decay_function = ["exponential", 'inverse_time', 'natural_exp']

[distribute]
strategy = ['off', 'default', 'one_device', 'mirrored', 'parameter_server', 'multi_worker_mirrored']
all_reduce_alg = ["nccl", "ring", "hierarchical_copy", "auto"]
