# This toml file defines the default values of the options.

precision = ['high', 'medium']

[dataset]
descriptor = ['eam', 'behler']

[nn]
activation = ["leaky_relu", 'relu', 'tanh', 'softsign', 'sigmoid', 'linear', 'elu']

[nn.atomic]
arch = ["AtomicResNN", 'AtomicNN']
input_normalizer = ["linear", 'arctan']

[nn.atomic.behler]
cutoff = ["cosine", "polynomial"]

[nn.eam]
arch = ["EamAlloyNN", "EamFsNN"]

[opt]
method = ["adam", 'rmsprop', 'adadelta']
decay_function = ["exponential", 'inverse_time', 'natural_exp']
