# This toml file defines the default values of the options.

precision = ['high', 'medium']

[dataset]
descriptor = ['eam', 'behler']

[nn]
activation = ["leaky_relu", 'relu', 'tanh', 'softsign', 'sigmoid', 'linear', 'elu']

[nn.atomic]
arch = ["AtomicResNN", 'AtomicNN']

[nn.atomic.behler]
cutoff_function = ["cosine", "polynomial"]

[nn.eam]
arch = ["EamAlloyNN", "EamFsNN", "AdpNN"]

[nn.loss.energy]
method = ["rmse", "logcosh"]

[nn.loss.forces]
method = ["rmse", "logcosh"]

[nn.loss.stress]
method = ["rmse", "logcosh", "rrmse"]

[nn.loss.total_pressure]
method = ["rmse", "logcosh"]

[opt]
method = ["adam", 'rmsprop', 'adadelta']
decay_function = ["exponential", 'inverse_time', 'natural_exp']
