# This toml file defines the default values of the options.

precision = 'high'
seed = 611

[dataset]
sqlite3 = "required"
name = "required"
descriptor = "required"
rc = 6.5
tfrecords_dir = "."
test_size = 0.2

[nn]
activation = "leaky_relu"
minimize = ['energy', 'forces']
export = ['energy', 'forces']
positive_energy_mode = false

[nn.loss.energy]
weight = 1.0
per_atom_loss = false

[nn.loss.forces]
weight = 1.0

[nn.loss.stress]
weight = 1.0

[nn.loss.total_pressure]
weight = 1.0

[nn.loss.l2]
weight = 0.01

[nn.atomic]
arch = "AtomicNN"
input_normalizer = false

[nn.atomic.behler]
angular = false
cutoff = 'cosine'
trainable = false
eta = [0.01, 0.1, 0.5, 1.0, 4.0]
beta = [0.005]
gamma = [1.0, -1.0]
zeta = [1.0, 4.0]

[nn.atomic.layers]

[nn.eam]
arch = "EamAlloyNN"

[nn.eam.rho]
[nn.eam.phi]
[nn.eam.embed]

[nn.eam.setfl]
nr = 10000
dr = 0.00065
nrho = 10000
drho = 0.001

[nn.eam.setfl.lattice.constant]
[nn.eam.setfl.lattice.type]

[opt]
method = "adam"
learning_rate = 0.01
decay_function = false
decay_rate = 0.95
decay_steps = 1000
staircase = false

[train]
restart = false
batch_size = 50
previous_checkpoint = false
shuffle = true
model_dir = "required"
max_checkpoints_to_keep = 20
train_steps = 10000
eval_steps = 1000
summary_steps = 100
log_steps = 100
profile_steps = 2000
