# This toml file defines the default values of the options.

[dataset]
sqlite3 = "required"
name = "required"
descriptor = "required"
rc = 6.5
tfrecords_dir = "."
test_size = 0.2

[nn]
activation = "leaky_relu"
minimize = ['energy', 'forces']

[nn.loss.weights]
l2 = 0.01
energy = 1.0
forces = 1.0
stress = 1.0
total_pressure = 1.0

[nn.atomic]
arch = "AtomicNN"
input_normalizer = false
export = ['energy', 'forces']

[nn.atomic.behler]
angular = false
cutoff = 'cosine'
eta = [0.01, 0.1, 0.5, 1.0, 4.0]
beta = [0.005]
gamma = [1.0, -1.0]
zeta = [4.0]

[nn.atomic.layers]

[nn.eam]
arch = "EamAlloyNN"

[nn.eam.rho]
[nn.eam.phi]
[nn.eam.embed]

[nn.eam.export]
nr = 10000
dr = 0.00065
nrho = 10000
drho = 0.001

[opt]
method = "adam"
learning_rate = 0.01
decay_function = false
decay_rate = 0.95
decay_steps = 1000
staircase = false

[train]
restart = false
batch_size = 50
previous_checkpoint = false
shuffle = true
model_dir = "required"
max_checkpoints_to_keep = 20
train_steps = 10000
eval_steps = 1000
summary_steps = 100
log_steps = 100
profile_steps = 2000
