# This toml file defines the default values of the options.

precision = "medium"
seed = 611
pair_style = "atomic/grap"
rcut = 6.0
acut = 4.0

[dataset]
sqlite3 = "required"
name = "required"
tfrecords_dir = "."
test_size = 0.2
serial = false

[nn]
minimize = ['energy', 'forces', 'stress']
export = ['energy', 'forces', 'stress']

[nn.loss]

[nn.loss.energy]
weight = 1.0
per_atom_loss = true
method = "rmse"

[nn.loss.eentropy]
weight = 1.0
per_atom_loss = true
method = "ylogy"

[nn.loss.free_energy]
weight = 1.0
per_atom_loss = true
method = "rmse"

[nn.loss.rose]
weight = 1.0
crystals = []
beta = []
p_target = []
E_target = []
dx = 0.01
xlo = 0.90
xhi = 1.02

[nn.loss.ediff]
references = []
crystals = []
diff = []
weight = 1.0
forces_weight = 1.0
method = "mae"

[nn.loss.eentropy_constraint]
crystals = []
weight = 1.0

[nn.loss.hessian_constraint]
crystals = []
forces_weight = 1.0
weight = 1.0

[nn.loss.forces]
weight = 1.0
method = "rmse"

[nn.loss.stress]
weight = 1.0
method = "rmse"

[nn.loss.total_pressure]
weight = 1.0
method = "rmse"

[nn.loss.l2]
weight = 0.00
decayed = false
decay_rate = 0.99
decay_steps = 10

[nn.loss.elastic]
crystals = []
weight = 0.1

[nn.loss.elastic.constraint]
use_kbar = true
forces_weight = 1.0
stress_weight = 0.1
tau = 1.0

[nn.atomic]
kernel_initializer = 'he_normal'
use_resnet_dt = true
use_atomic_static_energy = true
fixed_atomic_static_energy = false
minmax_scale = false
activation = "softplus"

[nn.atomic.finite_temperature]
activation = "softplus"
layers = [128, 128]

[nn.atomic.polar]
inner_layers = [128, 128]
polar_loss_weight = 1.0

[nn.atomic.deepmd]
rcs = 4.0
m1 = 100
m2 = 4
embedding_sizes = [20, 40, 80]
embedding_activation = 'tanh'

[nn.atomic.sf]
cutoff_function = 'cosine'
eta = [0.01, 0.1, 0.5, 1.0, 4.0]
omega = [0.0]
beta = [0.005]
gamma = [1.0, -1.0]
zeta = [1.0, 4.0]

[nn.atomic.grap]
moment_tensors = [0, 1, 2]
algorithm = 'pexp'
cutoff_function = 'cosine'
param_space_method = "pair"
legacy_mode = true

[nn.atomic.grap.sf]
eta = [0.1, 0.5, 1.0, 4.0]
omega = [0.0]

[nn.atomic.grap.density]
A = [1.0]
beta = [1.0, 2.0, 3.0, 4.0]
re = [4.0]

[nn.atomic.grap.morse]
D = [1.0]
gamma = [0.5, 0.6]
r0 = [1.5, 2.5]

[nn.atomic.grap.pexp]
rl = [1.0, 1.2, 1.4, 1.6, 1.8, 2.0, 2.2, 2.4, 2.6, 2.8, 3.0]
pl = [5.0, 4.6, 4.2, 3.8, 3.4, 3.0, 2.6, 2.2, 1.8, 1.4, 1.0]

[nn.atomic.grap.nn]
activation = "softplus"
layer_sizes = [32, 32, 32]
num_filters = 16
use_resnet_dt = true
ckpt = false
trainable = true

[nn.atomic.layers]

[nn.eam]
fixed_functions = []

[nn.eam.rho]
[nn.eam.phi]
[nn.eam.embed]
[nn.eam.dipole]
[nn.eam.quadrupole]

[nn.eam.setfl]
nr = 10000
dr = 0.00065
nrho = 10000
drho = 0.01

[nn.eam.setfl.lattice.constant]
[nn.eam.setfl.lattice.type]

[nn.tersoff]
file = "required"
symmetric_mixing = false

[opt]
method = "adam"
learning_rate = 0.001
decay_function = 'exponential'
decay_rate = 0.98
decay_steps = 10000
staircase = false

[opt.sgd]
momentum = 0.9
use_nesterov = true

[opt.adam]
beta1 = 0.9
beta2 = 0.999

[opt.nadam]
beta1 = 0.9
beta2 = 0.999

[opt.adadelta]
rho = 0.95

[opt.rmsprop]
decay = 0.9
momentum = 0.0

[opt.adamw]
decay = 1e-4

[train]
reset_global_step = true
batch_size = 25
shuffle = true
model_dir = "train"
max_checkpoints_to_keep = 20
train_steps = 10000
eval_steps = 1000
summary_steps = 100
log_steps = 100
profile_steps = 0

[train.ckpt]
checkpoint_filename = false
use_ema_variables = true
restore_all_variables = true
restore_optimizer_vars = true

[distribute]
strategy = "off"
num_workers = 1
all_reduce_alg = "nccl"
num_packs = 1
num_gpus = 0

[debug]
logging_level = 'info'
start_delay_secs = 300
throttle_secs = 60
allow_gpu_growth = true
allow_soft_placement = true
log_device_placement = false
meta_optimizer_timeout_ms = -1
