# This toml file defines the default values of the options.

precision = 'high'
seed = 611
pair_style = "required"
rcut = 6.5
acut = 4.0

[dataset]
sqlite3 = "required"
name = "required"
tfrecords_dir = "."
test_size = 0.2
serial = false

[nn]
minimize = ['energy', 'forces']
export = ['energy', 'forces']

[nn.loss]

[nn.loss.energy]
weight = 1.0
per_atom_loss = false
method = "rmse"

[nn.loss.rose]
weight = 1.0
crystals = []
beta = []
dx = 0.10
delta = 0.01

[nn.loss.forces]
weight = 1.0
method = "rmse"

[nn.loss.stress]
weight = 1.0
method = "rmse"

[nn.loss.total_pressure]
weight = 1.0
method = "rmse"

[nn.loss.l2]
weight = 0.00
decayed = false
decay_rate = 0.99
decay_steps = 10

[nn.loss.elastic]
crystals = []
weight = 0.1

[nn.loss.elastic.constraint]
use_kbar = true
forces_weight = 1.0
stress_weight = 0.1
tau = 1.0

[nn.atomic]
kernel_initializer = 'he_normal'
use_resnet_dt = false
use_atomic_static_energy = true
fixed_atomic_static_energy = false
activation = "softplus"

[nn.atomic.finite_temperature]
algorithm = "full"
activation = "softplus"
layers = [128, 128]
biased_eentropy = true
biased_internal_energy = false

[nn.atomic.deepmd]
rcs = 4.0
m1 = 100
m2 = 4
embedding_sizes = [20, 40, 80]
embedding_activation = 'tanh'

[nn.atomic.sf]
minmax_scale = false
angular = false
cutoff_function = 'cosine'
eta = [0.01, 0.1, 0.5, 1.0, 4.0]
omega = [0.0]
beta = [0.005]
gamma = [1.0, -1.0]
zeta = [1.0, 4.0]

[nn.atomic.grap]
moment_tensors = 0
algorithm = 'sf'
cutoff_function = 'cosine'
minmax_scale = false
param_space_method = "cross"

[nn.atomic.grap.sf]
eta = [0.1, 0.5, 1.0, 4.0]
omega = [0.0]

[nn.atomic.grap.density]
A = [1.0]
beta = [1.0, 2.0, 3.0, 4.0]
re = [4.0]

[nn.atomic.grap.morse]
D = [1.0]
gamma = [0.5, 0.6]
r0 = [1.5, 2.5]

[nn.atomic.grap.pexp]
rl = [1.0, 1.2, 1.4, 1.6, 1.8, 2.0, 2.2, 2.4, 2.6, 2.8, 3.0]
pl = [5.0, 4.6, 4.2, 3.8, 3.4, 3.0, 2.6, 2.2, 1.8, 1.4, 1.0]

[nn.atomic.layers]

[nn.eam]

[nn.eam.rho]
[nn.eam.phi]
[nn.eam.embed]
[nn.eam.dipole]
[nn.eam.quadrupole]

[nn.eam.setfl]
nr = 10000
dr = 0.00065
nrho = 10000
drho = 0.01

[nn.eam.setfl.lattice.constant]
[nn.eam.setfl.lattice.type]

[nn.tersoff]
file = "required"
symmetric_mixing = false

[opt]
method = "adam"
learning_rate = 0.01
decay_function = false
decay_rate = 0.95
decay_steps = 1000
staircase = false

[opt.sgd]
momentum = 0.9
use_nesterov = true

[opt.adam]
beta1 = 0.9
beta2 = 0.999

[opt.nadam]
beta1 = 0.9
beta2 = 0.999

[opt.adadelta]
rho = 0.95

[opt.rmsprop]
decay = 0.9
momentum = 0.0

[opt.adamw]
decay = 1e-4

[train]
reset_global_step = true
batch_size = 50
shuffle = true
model_dir = "train"
max_checkpoints_to_keep = 20
train_steps = 10000
eval_steps = 1000
summary_steps = 100
log_steps = 100
profile_steps = 2000

[train.ckpt]
checkpoint_filename = false
use_ema_variables = true
restore_all_variables = true

[distribute]
strategy = "off"
num_workers = 1
all_reduce_alg = "nccl"
num_packs = 1
num_gpus = 0

[debug]
logging_level = 'info'
start_delay_secs = 300
throttle_secs = 60
allow_gpu_growth = true
allow_soft_placement = true
log_device_placement = false
meta_optimizer_timeout_ms = -1
