# This toml file defines the default values of the options.

precision = 'high'
seed = 611

[dataset]
sqlite3 = "required"
name = "required"
descriptor = "required"
rc = 6.5
tfrecords_dir = "."
test_size = 0.2
serial = false

[nn]
activation = "leaky_relu"
minimize = ['energy', 'forces']
export = ['energy', 'forces', 'hessian']

[nn.loss]
equivalently_trusted = true

[nn.loss.energy]
weight = 1.0
per_atom_loss = false
method = "rmse"

[nn.loss.rose]
weight = 1.0
crystals = []
beta = []
dx = 0.10
delta = 0.01

[nn.loss.forces]
weight = 1.0
method = "rmse"

[nn.loss.stress]
weight = 1.0
method = "rmse"

[nn.loss.total_pressure]
weight = 1.0
method = "rmse"

[nn.loss.l2]
weight = 0.01
decayed = true
decay_rate = 0.99
decay_steps = 10

[nn.loss.elastic]
crystals = []
weight = 0.1

[nn.loss.elastic.constraint]
use_kbar = true
forces_weight = 1.0
stress_weight = 0.1

[nn.atomic]
arch = "AtomicNN"
kernel_initializer = 'he_normal'

[nn.atomic.resnet]
fixed_static_energy = false

[nn.atomic.behler]
angular = false
cutoff_function = 'cosine'
trainable = false
eta = [0.01, 0.1, 0.5, 1.0, 4.0]
omega = [0.0]
beta = [0.005]
gamma = [1.0, -1.0]
zeta = [1.0, 4.0]

[nn.atomic.layers]

[nn.eam]
arch = "EamAlloyNN"

[nn.eam.rho]
[nn.eam.phi]
[nn.eam.embed]

[nn.eam.setfl]
nr = 10000
dr = 0.00065
nrho = 10000
drho = 0.01

[nn.eam.setfl.lattice.constant]
[nn.eam.setfl.lattice.type]

[opt]
method = "adam"
learning_rate = 0.01
decay_function = false
decay_rate = 0.95
decay_steps = 1000
staircase = false

[train]
restart = true
batch_size = 50
previous_checkpoint = false
use_previous_ema_variables = true
shuffle = true
model_dir = "required"
max_checkpoints_to_keep = 20
train_steps = 10000
eval_steps = 1000
summary_steps = 100
log_steps = 100
profile_steps = 2000

[debug]
allow_gpu_growth = true
logging_level = 'info'
