[dataset]
sqlite3 = "AlFe.db"
name = "AlFe"
descriptor = "eam"
rc = 6.5
tfrecords_dir = "experiments/AlFe/fs"
test_size = 1000

[nn]
minimize = ['energy', 'forces', 'stress', 'elastic']
export = ['energy', 'forces', 'hessian', 'stress']

[nn.loss.stress]
method = 'logcosh'

[nn.loss.elastic]
crystals = ['Al']
weight = 0.1

[nn.loss.elastic.constraint]
use_kbar = false
forces_weight = 1.0
stress_weight = 0.01

[nn.eam]
arch = "EamFsNN"

[nn.eam.setfl]
nr = 10000
dr = 0.0006
nrho = 10000
drho = 0.002

[nn.eam.setfl.lattice.constant]
Al = 4.04527
Fe = 2.855312

[nn.eam.setfl.lattice.type]
Al = 'fcc'
Fe = 'bcc'

[nn.eam.rho]
AlAl = "msah11"
AlFe = [32, 32]
FeFe = "msah11"
FeAl = [32, 32]

[nn.eam.embed]
Al = "msah11"
Fe = "msah11"

[nn.eam.phi]
AlAl = "msah11"
FeAl = [32, 32]
FeFe = "msah11"

[train]
model_dir = "experiments/AlFe/fs/train"
