[dataset]
sqlite3 = "AlFe.db"
name = "AlFe"
descriptor = "eam"
rc = 6.5
k_max = 2
serial = true
tfrecords_dir = "experiments/AlFe/fs"
test_size = 1000

[nn.eam]
arch = "EamFsNN"

[nn.eam.export]
nr = 10000
dr = 0.0006
nrho = 10000
drho = 0.002

[nn.eam.export.lattice.constant]
Al = 4.04527
Fe = 2.855312

[nn.eam.export.lattice.type]
Al = 'fcc'
Fe = 'bcc'

[nn.eam.rho]
AlAl = "msah11"
AlFe = [32, 32]
FeFe = "msah11"
FeAl = [32, 32]

[nn.eam.embed]
Al = "msah11"
Fe = "msah11"

[nn.eam.phi]
AlAl = "msah11"
FeAl = [32, 32]
FeFe = "msah11"

[train]
model_dir = "experiments/AlFe/fs/train"
