seed = 1
precision = 'medium'

[dataset]
sqlite3 = "../../datasets/snap-Ni.db"
name = "Ni"
descriptor = "atomic"
rc = 6.5
tfrecords_dir = "deepmd"
test_size = 61

[nn]
activation = "softplus"
minimize = ['energy', 'forces', 'stress']
export = ['energy', 'forces', 'stress']

[nn.atomic]
arch = "DeepPotSE"
kernel_initializer = 'he_normal'

[nn.atomic.deepmd]
m1 = 50
m2 = 4
rcs = 4.0
embedding_activation = 'sigmoid'
embedding_sizes = [20, 40]

[nn.atomic.layers]
Ni = [64, 32]

[opt]
learning_rate = 0.01
decay_function = false
method = 'adam'

[train]
reset_global_step = true
batch_size = 25
shuffle = true
model_dir = "./model"
max_checkpoints_to_keep = 10
train_steps = 200
eval_steps = 200
summary_steps = 10
log_steps = 10
profile_steps = 0

[train.ckpt]
use_ema_variables = false
restore_all_variables = false
