[dataset]
sqlite3 = "datasets/qm7.db"
name = "qm7"
descriptor = "eam"
rc = 6.5
tfrecords_dir = "experiments/qm7-eam"
test_size = 1000

[nn]
activation = "leaky_relu"
l2_weight = 0.01

[nn.eam]
arch = "EamAlloyNN"

[nn.eam.export]
nr = 10000
dr = 0.00066
nrho = 10000
drho = 0.002

[nn.eam.rho]
C = [32, 32]
H = [32, 32]
N = [32, 32]
O = [32, 32]
S = [32, 32]

[nn.eam.embed]
C = [32, 32]
H = [32, 32]
N = [32, 32]
O = [32, 32]
S = [32, 32]

[nn.eam.phi]
CC = [32, 32]
CH = [32, 32]
CN = [32, 32]
CO = [32, 32]
CS = [32, 32]
HH = [32, 32]
HN = [32, 32]
HO = [32, 32]
HS = [32, 32]
NN = [32, 32]
NO = [32, 32]
NS = [32, 32]
OO = [32, 32]
OS = [32, 32]
SS = [32, 32]

[opt]
method = "adam"
learning_rate = 0.01
decay_function = "exponential"
decay_rate = 0.98
decay_steps = 1000
staircase = false

[train]
restart = false
batch_size = 50
shuffle = true
model_dir = "experiments/qm7-eam/train"
max_checkpoints_to_keep = 20
train_steps = 10000
eval_steps = 1000
summary_steps = 100
log_steps = 100
profile_steps = 2000
