precision = "medium"
pair_style = 'eam/alloy'
rcut = 6.0

[dataset]
sqlite3 = "../../tensoralloy/data/datasets/snap-Ni.db"
name = "snap_Ni"
test_size = 61
tfrecords_dir = 'temp'

[nn]
minimize = ['energy', 'forces', 'rose']
export = ['energy', 'forces', 'stress', 'hessian']

[nn.loss.l2]
weight = 0.01

[nn.loss.energy]
weight = 1.0
per_atom_loss = false

[nn.loss.rose]
crystals = ['Ni']
beta = [0.5e-2]

[nn.loss.forces]
weight = 3.0

[nn.eam.rho]
Ni = "zjw04"

[nn.eam.embed]
Ni = "zjw04"

[nn.eam.phi]
NiNi = "zjw04"

[nn.eam.setfl]
nr = 10000
dr = 0.0006
nrho = 10000
drho = 0.001

[opt]
method = 'sgd'
learning_rate = 0.00001
decay_function = "exponential"
decay_rate = 0.98

[opt.sgd]
use_nesterov = false

[train]
reset_global_step = true
batch_size = 20
shuffle = true
model_dir = "snap_Ni_zjw04"
train_steps = 10
max_checkpoints_to_keep = 5
eval_steps = 10
summary_steps = 5
log_steps = 50
profile_steps = 0

[train.ckpt]
checkpoint_filename = false
