precision = "medium"

[dataset]
sqlite3 = "../../datasets/snap-Ni.db"
name = "snap_Ni"
descriptor = "eam"
rc = 6.0
test_size = 61
tfrecords_dir = 'temp'

[nn]
minimize = ['energy', 'forces', 'rose']
export = ['energy', 'forces', 'stress', 'hessian']

[nn.loss]
equivalently_trusted = false

[nn.loss.l2]
weight = 0.01

[nn.loss.energy]
weight = 1.0
per_atom_loss = false

[nn.loss.rose]
crystals = ['Ni']
beta = [0.5e-2]

[nn.loss.forces]
weight = 3.0

[nn.eam]
arch = "EamAlloyNN"

[nn.eam.rho]
Ni = "zjw04"

[nn.eam.embed]
Ni = "zjw04"

[nn.eam.phi]
NiNi = "zjw04"

[nn.eam.setfl]
nr = 10000
dr = 0.0006
nrho = 10000
drho = 0.001

[opt]
learning_rate = 0.01
decay_function = "exponential"
decay_rate = 0.98

[train]
restart = true
batch_size = 20
shuffle = true
model_dir = "snap_Ni_zjw04"
previous_checkpoint = false
train_steps = 10
max_checkpoints_to_keep = 5
eval_steps = 10
summary_steps = 5
log_steps = 50
profile_steps = 0
