precision = "medium"

[dataset]
sqlite3 = "qm7.db"
name = "qm7"
rc = 6.5
test_size = 1000

[nn]
activation = "softplus"
minimize = ['energy']

[nn.loss.energy]
weight = 1.0
per_atom_loss = false

[nn.loss.l2]
weight = 0.00

[nn.atomic.behler]
angular = true
trainable = false
eta = [0.1, 0.5, 1.0, 2.0, 4.0, 8.0, 12.0, 16.0, 20.0, 40.0]
omega = [0.0]
beta = [0.1, 1.0]
gamma = [1.0, -1.0]
zeta = [1.0, 4.0]

[nn.atomic]
arch = "AtomicResNN"
minmax_scale = true
kernel_initializer = "he_normal"

[nn.atomic.layers]
C = [64, 32]
H = [64, 32]
N = [64, 32]
O = [64, 32]
S = [64, 32]

[opt]
learning_rate = 0.01
decay_function = "exponential"
decay_rate = 0.96
decay_steps = 2500
staircase = false

[train]
reset_global_step = true
batch_size = 100
shuffle = true
model_dir = "train"
train_steps = 100000
max_checkpoints_to_keep = 100
eval_steps = 10000
summary_steps = 100
log_steps = 100
profile_steps = 0
