#!/usr/bin/env python
# coding=utf-8
"""
An executable script for running experiments.
"""
from __future__ import print_function, absolute_import

from tensoralloy.cli import main

__author__ = 'Xin Chen'
__email__ = 'Bismarrck@me.com'


if __name__ == "__main__":
    main()
