#!/usr/bin/env python
# coding=utf-8
"""
An executable script for running experiments.
"""
from __future__ import print_function, absolute_import

import warnings
warnings.filterwarnings("ignore")

import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

import tensorflow as tf
tf.compat.v1.logging.set_verbosity(tf.compat.v1.logging.ERROR)
tf.logging.set_verbosity(tf.logging.ERROR)

from tensoralloy.cli.entry import main

__author__ = 'Xin Chen'
__email__ = 'Bismarrck@me.com'


if __name__ == "__main__":
    main()
